name: C++ Lint (Optimized)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-18

      - name: Generate compile_commands.json
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy (only your code)
        run: |
          find src/ test/ -name '*.cpp' -o -name '*.h' \
            | grep -v 'third_party' \
            | xargs clang-tidy-18 -p=build \
                --extra-arg=-Iinclude/ \
                --extra-arg=-std=c++20

#      - name: Optional - Run clang-format
#        run: |
#          find src/ test/ -name '*.cpp' -o -name '*.h' \
#            | grep -v 'third_party' \
#            | xargs clang-format --style=file --dry-run --Werror